### ISSUE TITLE
The README has a typo.

### ISSUE THREAD

**Issue by abielrodriguez** [udp-shim-nokia/curly-doodle#1]
The README mentions 3000 as the default port but its actually 30000 :

> NOTE: .lua file is configured to use UDP source/dest port **3000**. If you're using a different src/dst combination to deliver to a collector, change this port accordingly in the .lua file or modify your SROS router config to use port **3000**.

Simple change ;)

**Comment by udp-shim-nokia** [comment]
All fixed. Thank you for your attention!
